version: '2'

services:
  web:
    image: richarvey/nginx-php-fpm:1.4.1
    dns: 8.8.8.8
    ports:
      - "9000:80"
    links:
      - "database:db"
    volumes:
      - ./www:/var/www/html
      - ./shared/nginx.conf:/etc/nginx/nginx.conf
      - ./shared/nginx-site.conf:/etc/nginx/sites-enabled/default.conf
      - ./shared/php.ini:/usr/local/etc/php/php.ini
      - ./shared/wp-config.php:/var/www/html/wp-config.php
    environment:
      - PUID=1000
      - ERRORS=1

  myadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    dns: 8.8.8.8
    ports:
      - "9001:80"
    links:
      - "database:db"
    environment:
      - MYSQL_ROOT_PASSWORD

  database:
    image: mysql/mysql-server:5.7.18
    dns: 8.8.8.8
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./shared/dump.sql:/docker-entrypoint-initdb.d/a_dump.sql
      - ./shared/override.sql:/docker-entrypoint-initdb.d/b_override.sql
    environment:
    - MYSQL_DATABASE=carawonga
    - MYSQL_ROOT_HOST=%
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - NEW_HOST=localhost

  cli:
    image: pierreprinetti/wp-cli
    dns: 8.8.8.8
    links:
      - "database:db"
    volumes:
      - ./www:/wordpress
      - ./shared/wp-config.php:/wordpress/wp-config.php
    entrypoint: sleep 86400
    