version: '2'

services:
  web:
    image: richarvey/nginx-php-fpm:1.4.1
    ports:
      - "9000:80"
    links:
      - "database:db"
    volumes:
      - ./www:/var/www/html
      - ./shared/php.ini:/usr/local/etc/php/php.ini
      - ./shared/wp-config.php:/var/www/html/wp-config.php
    environment:
      - PUID=1000
    restart: on-failure

  myadmin:
    image: phpmyadmin/phpmyadmin:4.7.7-1
    ports:
      - "9001:80"
    links:
      - "database:db"
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: on-failure

  database:
    image: mysql/mysql-server:5.7.18
    volumes:
      # - ./mysql:/var/lib/mysql
      - ./shared/dump.sql:/docker-entrypoint-initdb.d/a_dump.sql
      - ./shared/cleanup.sql:/docker-entrypoint-initdb.d/b_cleanup.sql
    environment:
    - MYSQL_DATABASE=carawonga
    - MYSQL_ROOT_HOST=%
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - NEW_HOST=localhost
    restart: on-failure

  cli:
    image: pierreprinetti/wp-cli
    links:
      - "database:db"
    volumes:
      - ./www:/wordpress
      - ./shared/wp-config.php:/wordpress/wp-config.php
    entrypoint: sleep 86400
    restart: on-failure
    # wp --allow-root search-replace https://carawonga.com http://192.168.99.100:9000 --dry-run
    