version: '2'

services:
  web:
    image: kvaps/nginx-php-fpm
    ports:
      - "9999:80"
    links:
      - "database:db"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./shared/php.ini:/usr/local/etc/php/php.ini
      # - ./shared/wp-config.php:/usr/share/nginx/html/wp-config.php
    restart: on-failure

  database:
    image: mysql/mysql-server:5.7.18
    volumes:
      - ./mysql:/var/lib/mysql
      # - ./shared/dump.sql:/docker-entrypoint-initdb.d/a_dump.sql
      # - ./shared/cleanup.sql:/docker-entrypoint-initdb.d/c_cleanup.sql
    environment:
    - MYSQL_DATABASE=carawonga
    - MYSQL_ROOT_HOST=%
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    restart: on-failure
