apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: carawonga@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carawonga-hu
  namespace: default
spec:
  secretName: carawonga-hu-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: carawonga.hu
  dnsNames:
  - carawonga.hu
  - www.carawonga.hu
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carawonga-com
  namespace: default
spec:
  secretName: carawonga-com-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: carawonga.com
  dnsNames:
  - carawonga.com
  - www.carawonga.com
