apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: default
spec:
  acme:
    email: carawonga@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: traefik
          ingressTemplate:
            metadata:
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: web
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carawonga-hu
  namespace: default
spec:
  commonName: carawonga.hu
  dnsNames:
  - carawonga.hu
  - www.carawonga.hu
  issuerRef:
    name: letsencrypt
  secretName: carawonga-hu-tls
