---
additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=letsencrypt
  - --entrypoints.websecure.http.tls.domains[0].main=carawonga.hu
  - --entrypoints.websecure.http.tls.domains[0].sans=www.carawonga.hu
  - --certificatesresolvers.letsencrypt.acme.email=carawonga@gmail.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
  - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
      volumeMounts:
      - mountPath: /data
        name: data

ports:
  web:
    redirectTo: websecure

ingressRoute:
  dashboard:
    enabled: false
