################################################################
#
# Configuration sample for Traefik v2.
#
# For Traefik v1: https://github.com/traefik/traefik/blob/v1.7/traefik.sample.toml
#
################################################################
global:
  checkNewVersion: true
  sendAnonymousUsage: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
certificatesResolvers:
  carawongahu:
    acme:
      email: carawonga@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: websecure
